lambda-error-sns-sender/__init__.py,sha256=J4dNSO_Lah-WssTFLmdvY-wyv8rTX6k3TYfk7Kp1uQ8,27282
lambda-error-sns-sender/py.typed,sha256=AbpHGcgLb-kRsJGnwFEktk7uzpZOCcBY74-YBdrKVGs,1
lambda-error-sns-sender/_jsii/__init__.py,sha256=Z06VdWzVc8mItgH2etuStDsPYdB4aHxR1miWWMsW_a8,428
lambda-error-sns-sender/_jsii/lambda-error-sns-sender@0.0.36.jsii.tgz,sha256=o3VedL1g51NThkVB7Jn14hKfakKeXt-HUhHwkLXWEIo,35426
lambda_error_sns_sender-0.0.36.dist-info/LICENSE,sha256=z8d0m5b2O9McPEK1xHG_dWgUBT6EfBDz6wA0F7xSPTA,11358
lambda_error_sns_sender-0.0.36.dist-info/METADATA,sha256=cAd_QP7VJxiCTeVucHFVm0lPUJE0KFI5XiOou2RVqsk,2102
lambda_error_sns_sender-0.0.36.dist-info/WHEEL,sha256=5sUXSg9e4bi7lTLOHcm6QEYwO5TIF1TNbTSVFVjcJcc,92
lambda_error_sns_sender-0.0.36.dist-info/top_level.txt,sha256=FkMA9jPLJsN588vpcg5IZxGjGTXyTWVbDBZNa2cu0yI,24
lambda_error_sns_sender-0.0.36.dist-info/RECORD,,
